services:
  arcabot_chromadb:
    build:
      context: arcabot_chromadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./arcabot_chromadb/src:/usr/src/app
      - ./arcabot_chromadb/documents:/usr/src/app/documents
      - ./arcabot_fastapi/chroma_data:/opt/chroma_data

  arcabot_fastapi:
    build:
      context: arcabot_fastapi
      dockerfile: Dockerfile
    depends_on:
      - arcabot_chromadb
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./arcabot_fastapi/src:/usr/src/app

  arcabot_streamlit:
    build:
      context: arcabot_streamlit
      dockerfile: Dockerfile
    depends_on:
      - arcabot_fastapi
    env_file:
      - .env
    ports:
      - '8501:8501'
    volumes:
      - ./arcabot_streamlit/src:/usr/src/app