[project]
name = "pdfquery_chroma_init"
version = "0.1"
dependencies = [
    "chromadb==0.6.3",
    "langchain-community==0.3.20",
    "langchain-openai==0.3.11",
    "pypdf==5.4.0",
]

[project.optional-dependencies]
dev = ["black", "flake8"]